export default {
  currencies: [
    { code: "EUR", symbol:"€", "name": "Euro Member Countries" } ,
    { code: "GBP", symbol:"£", "name": "United Kingdom Pound" } ,
    { code: "USD", symbol:"$", "name": "United States Dollar" } ,
    { code: "AED", symbol:"Dhs", "name": "United Arab Emirates Dirham" } ,
    { code: "AFN", symbol:"؋", "name": "Afghanistan Afghani" } ,
    { code: "ALL", symbol:"Lek", "name": "Albania Lek" } ,
    { code: "AMD", symbol:"Դրամ", "name": "Armenia Dram" } ,
    { code: "ANG", symbol:"ƒ", "name": "Netherlands Antilles Guilder" } ,
    { code: "AOA", symbol:"kwanza", "name": "Angola Kwanza" } ,
    { code: "ARS", symbol:"$", "name": "Argentina Peso" } ,
    { code: "AUD", symbol:"$", "name": "Australia Dollar" } ,
    { code: "AWG", symbol:"ƒ", "name": "Aruba Guilder" } ,
    { code: "AZN", symbol:"&#8380", "name": "8380 20bc Azerbaijan Manat" } ,
    { code: "BAM", symbol:"KM", "name": "Bosnia and Herzegovina Convertible Marka" } ,
    { code: "BBD", symbol:"$", "name": "Barbados Dollar" } ,
    { code: "BDT", symbol:"?", "name": "Bangladesh Taka" } ,
    { code: "BGN", symbol:"лв", "name": "Bulgaria Lev" } ,
    { code: "BHD", symbol:"?", "name": "Bahrain Dinar" } ,
    { code: "BIF", symbol:"?", "name": "Burundi Franc" } ,
    { code: "BMD", symbol:"?", "name": "Bermuda Dollar" } ,
    { code: "BND", symbol:"$", "name": "Brunei Darussalam Dollar" } ,
    { code: "BOB", symbol:"$b", "name": "Bolivia Bolíviano" } ,
    { code: "BRL", symbol:"R$", "name": "Brazil Real" } ,
    { code: "BSD", symbol:"?", "name": "Bahamas Dollar" } ,
    { code: "BTN", symbol:"?", "name": "Bhutan Ngultrum" } ,
    { code: "BWP", symbol:"P", "name": "Botswana Pula" } ,
    { code: "BYN", symbol:"Br", "name": "Belarus Ruble" } ,
    { code: "BZD", symbol:"BZ$", "name": "Belize Dollar" } ,
    { code: "CAD", symbol:"$", "name": "Canada Dollar" } ,
    { code: "CDF", symbol:"?", "name": "Congo/Kinshasa Franc" } ,
    { code: "CHF", symbol:"CHF", "name": "Switzerland Franc" } ,
    { code: "CLP", symbol:"$", "name": "Chile Peso" } ,
    { code: "CNY", symbol:"¥", "name": "China Yuan Renminbi" } ,
    { code: "COP", symbol:"$", "name": "Colombia Peso" } ,
    { code: "CRC", symbol:"₡", "name": "Costa Rica Colon" } ,
    { code: "CUC", symbol:"?", "name": "Cuba Convertible Peso" } ,
    { code: "CUP", symbol:"₱", "name": "Cuba Peso" } ,
    { code: "CVE", symbol:"?", "name": "Cape Verde Escudo" } ,
    { code: "CZK", symbol:"Kč", "name": "Czech Republic Koruna" } ,
    { code: "DJF", symbol:"?", "name": "Djibouti Franc" } ,
    { code: "DKK", symbol:"kr", "name": "Denmark Krone" } ,
    { code: "DOP", symbol:"RD$", "name": "Dominican Republic Peso" } ,
    { code: "DZD", symbol:"?", "name": "Algeria Dinar" } ,
    { code: "EGP", symbol:"£", "name": "Egypt Pound" } ,
    { code: "ERN", symbol:"?", "name": "Eritrea Nakfa" } ,
    { code: "ETB", symbol:"?", "name": "Ethiopia Birr" } ,
    { code: "FJD", symbol:"$", "name": "Fiji Dollar" } ,
    { code: "FKP", symbol:"£", "name": "Falkland Islands (Malvinas) Pound" } ,

    { code: "GEL", symbol:"?", "name": "Georgia Lari" } ,
    { code: "GGP", symbol:"£", "name": "Guernsey Pound" } ,
    { code: "GHS", symbol:"¢", "name": "Ghana Cedi" } ,
    { code: "GIP", symbol:"£", "name": "Gibraltar Pound" } ,
    { code: "GMD", symbol:"?", "name": "Gambia Dalasi" } ,
    { code: "GNF", symbol:"?", "name": "Guinea Franc" } ,
    { code: "GTQ", symbol:"Q", "name": "Guatemala Quetzal" } ,
    { code: "GYD", symbol:"$", "name": "Guyana Dollar" } ,
    { code: "HKD", symbol:"$", "name": "Hong Kong Dollar" } ,
    { code: "HNL", symbol:"L", "name": "Honduras Lempira" } ,
    { code: "HRK", symbol:"kn", "name": "Croatia Kuna" } ,
    { code: "HTG", symbol:"?", "name": "Haiti Gourde" } ,
    { code: "HUF", symbol:"Ft", "name": "Hungary Forint" } ,
    { code: "IDR", symbol:"Rp", "name": "Indonesia Rupiah" } ,
    { code: "ILS", symbol:"₪", "name": "Israel Shekel" } ,
    { code: "IMP", symbol:"£", "name": "Isle of Man Pound" } ,
    { code: "INR", symbol:"?", "name": "India Rupee" } ,
    { code: "IQD", symbol:"?", "name": "Iraq Dinar" } ,
    { code: "IRR", symbol:"﷼", "name": "Iran Rial" } ,
    { code: "ISK", symbol:"kr", "name": "Iceland Krona" } ,
    { code: "JEP", symbol:"£", "name": "Jersey Pound" } ,
    { code: "JMD", symbol:"J$", "name": "Jamaica Dollar" } ,
    { code: "JOD", symbol:"?", "name": "Jordan Dinar" } ,
    { code: "JPY", symbol:"¥", "name": "Japan Yen" } ,
    { code: "KES", symbol:"?", "name": "Kenya Shilling" } ,
    { code: "KGS", symbol:"лв", "name": "Kyrgyzstan Som" } ,
    { code: "KHR", symbol:"៛", "name": "Cambodia Riel" } ,
    { code: "KMF", symbol:"?", "name": "Comorian Franc" } ,
    { code: "KPW", symbol:"₩", "name": "Korea (North) Won" } ,
    { code: "KRW", symbol:"₩", "name": "Korea (South) Won" } ,
    { code: "KWD", symbol:"?", "name": "Kuwait Dinar" } ,
    { code: "KYD", symbol:"$", "name": "Cayman Islands Dollar" } ,
    { code: "KZT", symbol:"лв", "name": "Kazakhstan Tenge" } ,
    { code: "LAK", symbol:"₭", "name": "Laos Kip" } ,
    { code: "LBP", symbol:"£", "name": "Lebanon Pound" } ,
    { code: "LKR", symbol:"₨", "name": "Sri Lanka Rupee" } ,
    { code: "LRD", symbol:"$", "name": "Liberia Dollar" } ,
    { code: "LSL", symbol:"?", "name": "Lesotho Loti" } ,
    { code: "LYD", symbol:"?", "name": "Libya Dinar" } ,
    { code: "MAD", symbol:"?", "name": "Morocco Dirham" } ,
    { code: "MDL", symbol:"?", "name": "Moldova Leu" } ,
    { code: "MGA", symbol:"?", "name": "Madagascar Ariary" } ,
    { code: "MKD", symbol:"ден", "name": "Macedonia Denar" } ,
    { code: "MMK", symbol:"?", "name": "Myanmar (Burma) Kyat" } ,
    { code: "MNT", symbol:"₮", "name": "Mongolia Tughrik" } ,
    { code: "MOP", symbol:"?", "name": "Macau Pataca" } ,
    { code: "MRU", symbol:"?", "name": "Mauritania Ouguiya" } ,
    { code: "MUR", symbol:"₨", "name": "Mauritius Rupee" } ,
    { code: "MVR", symbol:"?", "name": "Maldives (Maldive Islands) Rufiyaa" } ,
    { code: "MWK", symbol:"?", "name": "Malawi Kwacha" } ,
    { code: "MXN", symbol:"$", "name": "Mexico Peso" } ,
    { code: "MYR", symbol:"RM", "name": "Malaysia Ringgit" } ,
    { code: "MZN", symbol:"MT", "name": "Mozambique Metical" } ,
    { code: "NAD", symbol:"$", "name": "Namibia Dollar" } ,
    { code: "NGN", symbol:"₦", "name": "Nigeria Naira" } ,
    { code: "NIO", symbol:"C$", "name": "Nicaragua Cordoba" } ,
    { code: "NOK", symbol:"kr", "name": "Norway Krone" } ,
    { code: "NPR", symbol:"₨", "name": "Nepal Rupee" } ,
    { code: "NZD", symbol:"$", "name": "New Zealand Dollar" } ,
    { code: "OMR", symbol:"﷼", "name": "Oman Rial" } ,
    { code: "PAB", symbol:"B/.", "name": "Panama Balboa" } ,
    { code: "PEN", symbol:"S/.", "name": "Peru Sol" } ,
    { code: "PGK", symbol:"?", "name": "Papua New Guinea Kina" } ,
    { code: "PHP", symbol:"₱", "name": "Philippines Piso" } ,
    { code: "PKR", symbol:"₨", "name": "Pakistan Rupee" } ,
    { code: "PLN", symbol:"zł", "name": "Poland Zloty" } ,
    { code: "PYG", symbol:"Gs", "name": "Paraguay Guarani" } ,
    { code: "QAR", symbol:"﷼", "name": "Qatar Riyal" } ,
    { code: "RON", symbol:"lei", "name": "Romania Leu" } ,
    { code: "RSD", symbol:"Дин.", "name": "Serbia Dinar" } ,
    { code: "RUB", symbol:"&#8381", "name": " 8381\t20bd Russia Ruble" } ,
    { code: "RWF", symbol:"?", "name": "Rwanda Franc" } ,
    { code: "SAR", symbol:"﷼", "name": "Saudi Arabia Riyal" } ,
    { code: "SBD", symbol:"$", "name": "Solomon Islands Dollar" } ,
    { code: "SCR", symbol:"₨", "name": "Seychelles Rupee" } ,
    { code: "SDG", symbol:"?", "name": "Sudan Pound" } ,
    { code: "SEK", symbol:"kr", "name": "Sweden Krona" } ,
    { code: "SGD", symbol:"$", "name": "Singapore Dollar" } ,
    { code: "SHP", symbol:"£", "name": "Saint Helena Pound" } ,
    { code: "SLL", symbol:"?", "name": "Sierra Leone Leone" } ,
    { code: "SOS", symbol:"S", "name": "Somalia Shilling" } ,
    { code: "SPL", symbol:"?", "name": "Seborga Luigino" } ,
    { code: "SRD", symbol:"$", "name": "Suriname Dollar" } ,
    { code: "STN", symbol:"?", "name": "São Tomé and Príncipe Dobra" } ,
    { code: "SVC", symbol:"$", "name": "El Salvador Colon" } ,
    { code: "SYP", symbol:"£", "name": "Syria Pound" } ,
    { code: "SZL", symbol:"?", "name": "Swaziland Lilangeni" } ,
    { code: "THB", symbol:"฿", "name": "Thailand Baht" } ,
    { code: "TJS", symbol:"?", "name": "Tajikistan Somoni" } ,
    { code: "TMT", symbol:"?", "name": "Turkmenistan Manat" } ,
    { code: "TND", symbol:"?", "name": "Tunisia Dinar" } ,
    { code: "TOP", symbol:"?", "name": "Tonga Pa'anga" } ,
    { code: "TRY", symbol:"?", "name": "Turkey Lira" } ,
    { code: "TTD", symbol:"TT$", "name": "Trinidad and Tobago Dollar" } ,
    { code: "TVD", symbol:"$", "name": "Tuvalu Dollar" } ,
    { code: "TWD", symbol:"NT$", "name": "Taiwan New Dollar" } ,
    { code: "TZS", symbol:"?", "name": "Tanzania Shilling" } ,
    { code: "UAH", symbol:"₴", "name": "Ukraine Hryvnia" } ,
    { code: "UGX", symbol:"?", "name": "Uganda Shilling" } ,
    { code: "UYU", symbol:"$U", "name": "Uruguay Peso" } ,
    { code: "UZS", symbol:"лв", "name": "Uzbekistan Som" } ,
    { code: "VEF", symbol:"Bs", "name": "Venezuela Bolívar" } ,
    { code: "VND", symbol:"₫", "name": "Viet Nam Dong" } ,
    { code: "VUV", symbol:"?", "name": "Vanuatu Vatu" } ,
    { code: "WST", symbol:"?", "name": "Samoa Tala" } ,
    { code: "XAF", symbol:"?", "name": "Communauté Financière Africaine (BEAC) CFA Franc BEAC" } ,
    { code: "XCD", symbol:"?", "name": "East Caribbean Dollar" } ,
    { code: "XDR", symbol:"?", "name": "International Monetary Fund (IMF) Special Drawing Rights" } ,
    { code: "XOF", symbol:"?", "name": "Communauté Financière Africaine (BCEAO) Franc" } ,
    { code: "XPF", symbol:"?", "name": "Comptoirs Français du Pacifique (CFP) Franc" } ,
    { code: "YER", symbol:"﷼", "name": "Yemen Rial" } ,
    { code: "ZAR", symbol:"R", "name": "South Africa Rand" } ,
    { code: "ZMW", symbol:"?", "name": "Zambia Kwacha" } ,
    { code: "ZWD", symbol:"Z$", "name": "Zimbabwe Dollar"}
  ],
};


